ecommerce/core/urls.py
from django.urls import path, include
from . import views

app_name = "core"

urlpatterns = [
    # Home Page
    path("", views.index, name="index"),
    # Product
    path("products/", views.product_list_view, name="product-list"),
    path("product/<pid>/", views.product_detail_view, name="product-detail"),
    # Category
    path("category/", views.category_list_view, name="category-list"),
    path(
        "category/<cid>/",
        views.category_product_list_view,
        name="category-product-list",
    ),
    # Vendor
    path("vendor/", views.vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", views.vendor_detail_view, name="vendor-detail"),
    # Tag
    path("products/tag/<slug:tag_slug>/", views.tag_list_view, name="tag-list"),
    # add review
    path("ajax-add-review/<int:pid>/", views.ajax_add_review, name="ajax-add-review"),
    # search
    path("search/", views.search_view, name="search"),
    # filter products
    path("filter-products/", views.filter_product, name="filter-products"),
    # add to cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    # cart page
    path("cart/", views.cart_view, name="cart"),
    path("cart/clear/", views.clear_cart, name="clear-cart"),
    # delete product from cart
    path("delete-from-cart/", views.delete_item_from_cart, name="delete-from-cart"),
    # update cart
    path("update-cart/", views.update_cart, name="update-cart"),
    # checkout
    path("checkout/", views.checkout_view, name="checkout"),
    # midtrans
    # path(
    #     "create-transaction/",
    #     views.transaction_midtrans_view,
    #     name="transaction_midtrans",
    # ),
    # paypal
    # path("paypal/", include("paypal.standard.ipn.urls")),
    # payment completed
    # path("payment-completed/", views.payment_completed_view, name="payment-completed"),
    # # payment failed
    # path("payment-failed/", views.payment_failed_view, name="payment-failed"),
    # midtrans
    path(
        "payments/create-snap-transaction/",
        views.create_snap_transaction,
        name="create_snap_transaction",
    ),
    path(
        "payments/notification/",
        views.midtrans_notification,
        name="midtrans_notification",
    ),
    path("payments/finish/", views.payment_finish, name="payment_finish"),
    path("payments/unfinish/", views.payment_unfinish, name="payment_unfinish"),
    path("payments/error/", views.payment_error, name="payment_error"),
    path(
        "payments/cancel-temp-order/", views.cancel_temp_order, name="cancel_temp_order"
    ),
    path("payments/invoice/<int:order_id>", views.invoice_pdf, name="payments-invoice"),
    # dashboard
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path(
        "dashboard/order/<int:id>/",
        views.order_detail_modal,
        name="order-detail-modal",
    ),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/core/forms.py
from django import forms
from core.models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "placeholder": "Write Review Here",
            }
        )
    )

    class Meta:
        model = ProductReview
        fields = ["review", "rating"]

ecommerce/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from core.models import (
    Product,
    Category,
    Vendor,
    ProductReview,
    CartOrder,
    CartOrderItems,
)
from django.db.models import Count, Avg, Q
from taggit.models import Tag
from core.forms import ProductReviewForm
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse
from django.template.loader import render_to_string
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles import finders
import base64, json, requests, hashlib, hmac
from weasyprint import HTML, CSS


def index(request):
    products = Product.objects.filter(
        product_status="published", featured=True
    ).order_by("-date")

    context = {
        "products": products,
    }

    return render(request, "core/index.html", context)


# Product Views
def product_list_view(request):
    products = Product.objects.filter(product_status="published").order_by("-date")

    context = {
        "products": products,
    }

    return render(request, "core/product-list.html", context)


def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    product_images = product.product_images.all()
    products = Product.objects.filter(category=product.category).exclude(pid=pid)

    # get product reviews
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    for r in reviews:
        r.rating_width = r.rating * 20

    # get average rating review
    avg_rating = ProductReview.objects.filter(product=product).aggregate(
        rating=Avg("rating")
    )
    avg_rating_data = avg_rating["rating"] or 0
    rating_width = (avg_rating_data / 5) * 100

    # rating count
    # hitung total review
    total_reviews = ProductReview.objects.filter(product=product).count()

    # hitung jumlah tiap bintang (1–5)
    rating_counts = (
        ProductReview.objects.filter(product=product)
        .values("rating")
        .annotate(count=Count("rating"))
    )

    # bikin list dari 5 → 1
    progres_data = []
    for star in range(5, 0, -1):
        count = next((r["count"] for r in rating_counts if r["rating"] == star), 0)
        percent = (count / total_reviews) * 100 if total_reviews else 0
        progres_data.append({"star": star, "percent": percent})

    # product review form
    product_review_form = ProductReviewForm()

    context = {
        "product": product,
        "product_images": product_images,
        "products": products,
        "reviews": reviews,
        "avg_rating": avg_rating,
        "product_review_form": product_review_form,
        "avg_rating_data": avg_rating_data,
        "rating_width": rating_width,
        "progres_data": progres_data,
    }

    return render(request, "core/product-detail.html", context)


# Category Views
def category_list_view(request):
    # categories = Category.objects.all()
    categories = Category.objects.all().annotate(product_count=Count("products"))

    context = {
        "categories": categories,
    }

    return render(request, "core/category-list.html", context)


def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(
        product_status="published", category=category
    ).order_by("-date")

    context = {
        "products": products,
        "category": category,
    }

    return render(request, "core/category-product-list.html", context)


# Vendor Views
def vendor_list_view(request):
    vendors = Vendor.objects.all()

    context = {
        "vendors": vendors,
    }

    return render(request, "core/vendor-list.html", context)


def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    # vendor = get_object_or_404(Vendor, vid=vid)
    products = Product.objects.filter(
        vendor=vendor, product_status="published"
    ).order_by("-date")

    context = {
        "vendor": vendor,
        "products": products,
    }

    return render(request, "core/vendor-detail.html", context)


# Other Views
def tag_list_view(request, tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-date")

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        "products": products,
        "tag": tag,
    }

    return render(request, "core/tag.html", context)


def ajax_add_review(request, pid):
    if not request.user.is_authenticated:
        return JsonResponse(
            {"bool": False, "error": "Anda harus login untuk memberi review."}
        )

    product = Product.objects.get(pk=pid)
    user = request.user

    review = ProductReview.objects.create(
        user=user,
        product=product,
        review=request.POST["review"],
        rating=request.POST["rating"],
    )

    average_reviews = ProductReview.objects.filter(product=product).aggregate(
        rating=Avg("rating")
    )

    context = {
        "user": user.username,
        "review": request.POST["review"],
        "rating": request.POST["rating"],
    }

    return JsonResponse(
        {
            "bool": True,
            "context": context,
            "average_reviews": average_reviews,
        }
    )


def search_view(request):
    query = request.GET.get("q")
    cat_cid = request.GET.get("category")
    products = Product.objects.filter(
        Q(title__icontains=query) | Q(description__icontains=query)
    ).order_by("-date")

    if cat_cid:
        products = products.filter(category__cid=cat_cid)

    context = {"products": products, "query": query}

    return render(request, "core/search.html", context)


def filter_product(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")
    min_price = request.GET.get("min_price")
    max_price = request.GET.get("max_price")

    products = (
        Product.objects.filter(product_status="published").order_by("-id").distinct()
    )

    if min_price and max_price:
        products = products.filter(price__gte=min_price, price__lte=max_price)

    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()

    data = render_to_string("core/async/product-list.html", {"products": products})
    count = products.count()

    return JsonResponse({"data": data, "count": count})


def add_to_cart(request):
    cart_product = {}

    product_id = str(request.GET["id"])

    try:
        new_qty = int(request.GET["qty"])
        if new_qty < 1:
            new_qty = 1
    except (ValueError, TypeError):
        new_qty = 1

    cart_product[str(request.GET["id"])] = {
        "title": request.GET["title"],
        "qty": new_qty,
        "price": request.GET["price"],
        "pid": request.GET["pid"],
        "image": request.GET["image"],
    }

    if "cart_data_obj" in request.session:
        if product_id in request.session["cart_data_obj"]:
            cart_data = request.session["cart_data_obj"]

            current_qty = int(cart_data[product_id]["qty"])
            cart_data[product_id]["qty"] = current_qty + new_qty

            # cart_data[str(request.GET["id"])]["qty"] = int(
            #     cart_product[str(request.GET["id"])]["qty"]
            # )
            # cart_data.update(cart_data)
            request.session["cart_data_obj"] = cart_data
        else:
            cart_data = request.session["cart_data_obj"]
            cart_data.update(cart_product)
            request.session["cart_data_obj"] = cart_data
    else:
        request.session["cart_data_obj"] = cart_product

    return JsonResponse(
        {
            "data": request.session["cart_data_obj"],
            "totalcartitems": len(request.session["cart_data_obj"]),
        }
    )


def cart_view(request):
    cart_total_amount = 0

    if "cart_data_obj" in request.session:
        for product_id, item in request.session["cart_data_obj"].items():
            price_rep = item["price"].strip().replace(",", "")
            subtotal = int(price_rep) * int(item["qty"])
            item["price"] = price_rep
            item["subtotal"] = subtotal
            cart_total_amount += subtotal
        return render(
            request,
            "core/cart.html",
            {
                "cart_data": request.session["cart_data_obj"],
                "totalcartitems": len(request.session["cart_data_obj"]),
                "cart_total_amount": cart_total_amount,
            },
        )
    else:
        return render(
            request,
            "core/cart.html",
            {
                "cart_data": {},
                "totalcartitems": 0,
                "cart_total_amount": cart_total_amount,
            },
        )


def delete_item_from_cart(request):
    product_id = str(request.GET["id"])

    if "cart_data_obj" in request.session:
        if product_id in request.session["cart_data_obj"]:
            cart_data = request.session["cart_data_obj"]
            del request.session["cart_data_obj"][product_id]
            request.session["cart_data_obj"] = cart_data

    cart_total_amount = 0
    if "cart_data_obj" in request.session:
        for product_id, item in request.session["cart_data_obj"].items():
            price_rep = item["price"].strip().replace(",", "")
            subtotal = int(price_rep) * int(item["qty"])
            item["price"] = price_rep
            item["subtotal"] = subtotal
            cart_total_amount += subtotal

    context = render_to_string(
        "core/async/cart-list.html",
        {
            "cart_data": request.session["cart_data_obj"],
            "totalcartitems": len(request.session["cart_data_obj"]),

ecommerce/templates/core/payment-error.html
{% extends "partials/base.html" %}
<!-- prettier-ignore -->
{% load static %}
{% block content %}
<main class="main page-404">
  <div class="page-content pt-150 pb-150">
    <div class="container">
      <div class="row">
        <div class="col-xl-8 col-lg-10 col-md-12 m-auto text-center">
          <p class="mb-20">
            {% comment %}
            <img
              src="{% static 'assets/imgs/page/page-404.png' %}"
              alt=""
              class="hover-up"
            />
          </p>
          {% endcomment %}
          <h1 class="display-2 mb-30">Payment Failed</h1>
          <p class="font-lg text-grey-700 mb-30">
            Try again with a different payment method
          </p>
          <a
            class="btn btn-default submit-auto-width font-xs hover-up mt-30"
            href="index.html"
            ><i class="fi-rs-home mr-5"></i> Back To Home Page</a
          >
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

ecommerce/templates/core/payment-finish.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Nest - Multipurpose eCommerce HTML Template</title>
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta property="og:title" content="" />
    <meta property="og:type" content="" />
    <meta property="og:url" content="" />
    <meta property="og:image" content="" />
    <!-- Favicon -->
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="{% static 'assets/imgs/theme/favicon.svg' %}"
    />
    <!-- Template CSS -->
    <link
      rel="stylesheet"
      href="{% static 'assets/css/plugins/slider-range.css' %}"
    />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
  </head>

  <body>
    <div class="invoice invoice-content invoice-6">
      <div class="back-top-home hover-up mt-30 ml-30">
        <a class="hover-up" href="{% url 'core:index' %}"
          ><i class="fi-rs-home mr-5"></i> Homepage</a
        >
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="invoice-inner">
              <div class="invoice-info" id="invoice_wrapper">
                <div class="invoice-header">
                  <div class="row align-items-center">
                    <div class="col-md-6">
                      <div class="logo">
                        <a href="index.html" class="mr-20"
                          ><img
                            src="{% static 'assets/imgs/theme/logo.svg' %}"
                            alt="logo"
                        /></a>
                      </div>
                    </div>
                    <div class="col-md-6 text-end">
                      <h2 class="mb-0">INVOICE</h2>
                    </div>
                  </div>
                  <div class="row align-items-center">
                    <div class="col-md-6">
                      <div class="text">
                        205 North, Suite 810, Chicago, USA<br />
                        <abbr title="Phone">Phone:</abbr> (+123) 456-7890<br />
                      </div>
                    </div>
                    <div class="col-md-6 text-end">
                      <strong class="text-brand">Webz Poland</strong> <br />
                      Madalinskiego 871-101 Szczecin, Poland<br />
                      <abbr title="Email">Email: </abbr>nfo@webz.com.pl
                    </div>
                  </div>
                  <div class="row mt-20">
                    <div class="col-12">
                      <div class="hr mb-10"></div>
                    </div>
                    <div class="col-lg-4">
                      <strong class="text-brand"> Invoice No:</strong> {{ order_id }}
                    </div>
                    <div class="col-lg-4">
                      <strong class="text-brand"> Date:</strong> {{ order_date|date:"d M Y, H:i" }}
                    </div>
                    <div class="col-lg-4">
                      <strong class="text-brand"> Payment Method:</strong>
                      {{ payment_method }}
                    </div>
                    <div class="col-12">
                      <div class="hr mt-10"></div>
                    </div>
                  </div>
                </div>
                <div class="invoice-center">
                  <div class="table-responsive">
                    <table class="table table-striped invoice-table">
                      <thead class="bg-active">
                        <tr>
                          <th>Item Item</th>
                          <th class="text-center">Unit Price</th>
                          <th class="text-center">Quantity</th>
                          <th class="text-right">Amount</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for i in items %}
                        <tr>
                          <td>
                            <div class="item-desc-1">
                              <span>{{ i.item }}</span>
                            </div>
                          </td>
                          <td class="text-center">Rp{{  i.price|floatformat|intcomma }}</td>
                          <td class="text-center">{{ i.qty }}</td>
                          <td class="text-right">Rp{{  i.total|floatformat|intcomma }}</td>
                        </tr>
                        {% endfor %}
                          <td colspan="3" class="text-end f-w-600">SubTotal</td>
                          <td class="text-right">Rp{{  subtotal|floatformat|intcomma }}</td>
                        </tr>
                        <tr>
                          <td colspan="3" class="text-end f-w-600">
                            Grand Total
                          </td>
                          <td class="text-right f-w-600">Rp{{ grand_total|floatformat|intcomma }}</td>
                        </tr> 
                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="invoice-bottom pb-80">
                  <div class="row">
                    <div class="col-md-6">
                      <h6 class="mb-15">Invoice Infor</h6>
                      <p class="font-sm">
                        <strong>Date:</strong> {{ order_date|date:"d M Y, H:i" }}<br />
                        <strong>Invoice No:</strong> {{ order_id }}<br />
                      </p>
                    </div>
                    <div class="col-md-6 text-end">
                      <h6 class="mb-15">Total Amount</h6>
                      <h3 class="mt-0 mb-0 text-brand">Rp{{ grand_total|floatformat|intcomma }}</h3>
                    </div>
                  </div>
                  <div class="row text-center">
                    <div class="col-12">
                      <div class="hr mt-30 mb-30"></div>
                      <p class="mb-0 text-muted">
                        <strong>Hallo {{ request.user|title }} </strong>Thank you for your order.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="invoice-btn-section clearfix d-print-none">
                <a
                  href="javascript:window.print()"
                  class="btn btn-lg btn-custom btn-print hover-up"
                >
                  <img
                    src="{% static 'assets/imgs/theme/icons/icon-print.svg' %}"
                    alt=""
                  />
                  Print
                </a>
                <a
                  href="{% url 'core:payments-invoice' %}"
                  target="_blank"
                  id="invoice_download_btn"
                  class="btn btn-lg btn-custom btn-download hover-up"
                >
                  <img
                    src="{% static 'assets/imgs/theme/icons/icon-download.svg' %}"
                    alt=""
                  />
                  Download
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Vendor JS-->
    <script src="{% static 'assets/js/vendor/modernizr-3.6.0.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery-migrate-3.3.0.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/slick.js' %}"></script>
    <script src="{% static 'assets/js/plugins/jquery.syotimer.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/wow.js' %}"></script>
    <script src="{% static 'assets/js/plugins/slider-range.js' %}"></script>
    <script src="{% static 'assets/js/plugins/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'assets/js/plugins/magnific-popup.js' %}"></script>
    <script src="{% static 'assets/js/plugins/select2.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/waypoints.js' %}"></script>
    <script src="{% static 'assets/js/plugins/counterup.js' %}"></script>
    <script src="{% static 'assets/js/plugins/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/images-loaded.js' %}"></script>
    <script src="{% static 'assets/js/plugins/isotope.js' %}"></script>
    <script src="{% static 'assets/js/plugins/scrollup.js' %}"></script>
    <script src="{% static 'assets/js/plugins/jquery.vticker-min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/jquery.theia.sticky.js' %}"></script>
    <script src="{% static 'assets/js/plugins/jquery.elevatezoom.js' %}"></script>
    <!-- Invoice JS -->
    <script src="{% static 'assets/js/invoice/jspdf.min.js' %}"></script>
    <script src="{% static 'assets/js/invoice/invoice.js' %}"></script>

    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'assets/js/shop.js' %}"></script>
    <script src="{% static 'assets/js/function.js' %}"></script>
  </body>
</html>

ecommerce/templates/core/vendor-list.html
{% extends "partials/base.html" %}
<!-- prettier-ignore -->
{% load static %}
{% block content %}
<main class="main pages mb-80">
  <div class="page-header breadcrumb-wrap">
    <div class="container">
      <div class="breadcrumb">
        <a href="{% url 'core:index' %}" rel="nofollow"
          ><i class="fi-rs-home mr-5"></i>Home</a
        >
        <span></span> Vendors
      </div>
    </div>
  </div>
  <div class="page-content pt-50">
    <div class="container">
      <div class="archive-header-2 text-center">
        <h1 class="display-2 mb-50">Vendors List</h1>
        <div class="row">
          <div class="col-lg-5 mx-auto">
            <div class="sidebar-widget-2 widget_search mb-50">
              <div class="search-form">
                <form action="#">
                  <input
                    type="text"
                    placeholder="Search vendors (by name or ID)..."
                  />
                  <button type="submit"><i class="fi-rs-search"></i></button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row mb-50">
        <div class="col-12 col-lg-8 mx-auto">
          <div class="shop-product-fillter">
            <div class="totall-product">
              <!-- prettier-ignore -->
              <p>
                We have
                <strong class="text-brand">{{ vendors.count }}</strong> vendor{{ vendors.count|pluralize }}
                now
              </p>
            </div>
            <div class="sort-by-product-area">
              <div class="sort-by-cover mr-10">
                <div class="sort-by-product-wrap">
                  <div class="sort-by">
                    <span><i class="fi-rs-apps"></i>Show:</span>
                  </div>
                  <div class="sort-by-dropdown-wrap">
                    <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                  </div>
                </div>
                <div class="sort-by-dropdown">
                  <ul>
                    <li><a class="active" href="#">50</a></li>
                    <li><a href="#">100</a></li>
                    <li><a href="#">150</a></li>
                    <li><a href="#">200</a></li>
                    <li><a href="#">All</a></li>
                  </ul>
                </div>
              </div>
              <div class="sort-by-cover">
                <div class="sort-by-product-wrap">
                  <div class="sort-by">
                    <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                  </div>
                  <div class="sort-by-dropdown-wrap">
                    <span>
                      Featured <i class="fi-rs-angle-small-down"></i
                    ></span>
                  </div>
                </div>
                <div class="sort-by-dropdown">
                  <ul>
                    <li><a class="active" href="#">Mall</a></li>
                    <li><a href="#">Featured</a></li>
                    <li><a href="#">Preferred</a></li>
                    <li><a href="#">Total items</a></li>
                    <li><a href="#">Avg. Rating</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row vendor-grid">
        {% for ven in vendors %}
        <div class="col-lg-6 col-md-6 col-12 col-sm-6">
          <div class="vendor-wrap style-2 mb-40">
            <div
              class="product-badges product-badges-position product-badges-mrg"
            >
              <span class="hot">Mall</span>
            </div>
            <div class="vendor-img-action-wrap">
              <div class="vendor-img">
                <a href="{% url 'core:vendor-detail' ven.vid %}">
                  <img
                    class="default-img"
                    src="{{ ven.image.url }}"
                    alt="{{ ven.title }}"
                  />
                </a>
              </div>
              <div class="mt-10">
                <!-- prettier-ignore -->
                <span class="font-small total-product"
                  >{{ ven.products.count }} product{{  ven.products.count|pluralize }}</span
                >
              </div>
            </div>
            <div class="vendor-content-wrap">
              <div class="mb-30">
                <div class="product-category">
                  <span class="text-muted">Since {{ ven.date|date:"Y" }}</span>
                </div>
                <h4 class="mb-5">
                  <a href="{% url 'core:vendor-detail' ven.vid %}"
                    >{{ ven.title }}</a
                  >
                </h4>
                <div class="product-rate-cover">
                  <div class="product-rate d-inline-block">
                    <div class="product-rating" style="width: 90%"></div>
                  </div>
                  <span class="font-small ml-5 text-muted"> (4.0)</span>
                </div>
                <div
                  class="vendor-info d-flex justify-content-between align-items-end mt-30"
                >
                  <ul class="contact-infor text-muted">
                    <li>
                      <img
                        src="{% static 'assets/imgs/theme/icons/icon-location.svg' %}"
                        alt=""
                      /><strong>Address: </strong>
                      <span>{{ ven.address }}</span>
                    </li>
                    <li>
                      <img
                        src="{% static 'assets/imgs/theme/icons/icon-contact.svg' %}"
                        alt=""
                      /><strong>Call Us:</strong><span>{{ ven.contact }}</span>
                    </li>
                  </ul>
                  {% comment %}
                  <a href="vendor-details-1.html" class="btn btn-xs"
                    >Visit Store <i class="fi-rs-arrow-small-right"></i
                  ></a>
                  {% endcomment %}
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--end vendor card-->
        {% endfor %}
      </div>
      {% comment %}
      <div class="pagination-area mt-20 mb-20">
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-start">
            <li class="page-item">
              <a class="page-link" href="#"
                ><i class="fi-rs-arrow-small-left"></i
              ></a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active">
              <a class="page-link" href="#">2</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link dot" href="#">...</a></li>
            <li class="page-item"><a class="page-link" href="#">6</a></li>
            <li class="page-item">
              <a class="page-link" href="#"
                ><i class="fi-rs-arrow-small-right"></i
              ></a>
            </li>
          </ul>
        </nav>
      </div>
      {% endcomment %}
    </div>
  </div>
</main>
{% endblock content %}