ecommerce/core/urls.py
from django.urls import path, include
from . import views

app_name = "core"

urlpatterns = [
    # Home Page
    path("", views.index, name="index"),
    # Product
    path("products/", views.product_list_view, name="product-list"),
    path("product/<pid>/", views.product_detail_view, name="product-detail"),
    # Category
    path("category/", views.category_list_view, name="category-list"),
    path(
        "category/<cid>/",
        views.category_product_list_view,
        name="category-product-list",
    ),
    # Vendor
    path("vendor/", views.vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", views.vendor_detail_view, name="vendor-detail"),
    # Tag
    path("products/tag/<slug:tag_slug>/", views.tag_list_view, name="tag-list"),
    # add review
    path("ajax-add-review/<int:pid>/", views.ajax_add_review, name="ajax-add-review"),
    # search
    path("search/", views.search_view, name="search"),
    # filter products
    path("filter-products/", views.filter_product, name="filter-products"),
    # add to cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    # cart page
    path("cart/", views.cart_view, name="cart"),
    path("cart/clear/", views.clear_cart, name="clear-cart"),
    # delete product from cart
    path("delete-from-cart/", views.delete_item_from_cart, name="delete-from-cart"),
    # update cart
    path("update-cart/", views.update_cart, name="update-cart"),
    # checkout
    path("checkout/", views.checkout_view, name="checkout"),
    # midtrans
    # path(
    #     "create-transaction/",
    #     views.transaction_midtrans_view,
    #     name="transaction_midtrans",
    # ),
    # paypal
    # path("paypal/", include("paypal.standard.ipn.urls")),
    # payment completed
    # path("payment-completed/", views.payment_completed_view, name="payment-completed"),
    # # payment failed
    # path("payment-failed/", views.payment_failed_view, name="payment-failed"),
    # midtrans
    path(
        "payments/create-snap-transaction/",
        views.create_snap_transaction,
        name="create_snap_transaction",
    ),
    path(
        "payments/notification/",
        views.midtrans_notification,
        name="midtrans_notification",
    ),
    path("payments/finish/", views.payment_finish, name="payment_finish"),
    path("payments/unfinish/", views.payment_unfinish, name="payment_unfinish"),
    path("payments/error/", views.payment_error, name="payment_error"),
    path(
        "payments/cancel-temp-order/", views.cancel_temp_order, name="cancel_temp_order"
    ),
    path("payments/invoice/<int:order_id>", views.invoice_pdf, name="payments-invoice"),
    # dashboard
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path(
        "dashboard/order/<int:id>/",
        views.order_detail_modal,
        name="order-detail-modal",
    ),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/core/forms.py
from django import forms
from core.models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "placeholder": "Write Review Here",
            }
        )
    )

    class Meta:
        model = ProductReview
        fields = ["review", "rating"]

ecommerce/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from core.models import (
    Product,
    Category,
    Vendor,
    ProductReview,
    CartOrder,
    CartOrderItems,
)
from django.db.models import Count, Avg, Q
from taggit.models import Tag
from core.forms import ProductReviewForm
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse
from django.template.loader import render_to_string
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles import finders
import base64, json, requests, hashlib, hmac
from weasyprint import HTML, CSS


def index(request):
    products = Product.objects.filter(
        product_status="published", featured=True
    ).order_by("-date")

    context = {
        "products": products,
    }

    return render(request, "core/index.html", context)


# Product Views
def product_list_view(request):
    products = Product.objects.filter(product_status="published").order_by("-date")

    context = {
        "products": products,
    }

    return render(request, "core/product-list.html", context)


def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    product_images = product.product_images.all()
    products = Product.objects.filter(category=product.category).exclude(pid=pid)

    # get product reviews
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    for r in reviews:
        r.rating_width = r.rating * 20

    # get average rating review
    avg_rating = ProductReview.objects.filter(product=product).aggregate(
        rating=Avg("rating")
    )
    avg_rating_data = avg_rating["rating"] or 0
    rating_width = (avg_rating_data / 5) * 100

    # rating count
    # hitung total review
    total_reviews = ProductReview.objects.filter(product=product).count()

    # hitung jumlah tiap bintang (1–5)
    rating_counts = (
        ProductReview.objects.filter(product=product)
        .values("rating")
        .annotate(count=Count("rating"))
    )

    # bikin list dari 5 → 1
    progres_data = []
    for star in range(5, 0, -1):
        count = next((r["count"] for r in rating_counts if r["rating"] == star), 0)
        percent = (count / total_reviews) * 100 if total_reviews else 0
        progres_data.append({"star": star, "percent": percent})

    # product review form
    product_review_form = ProductReviewForm()

    context = {
        "product": product,
        "product_images": product_images,
        "products": products,
        "reviews": reviews,
        "avg_rating": avg_rating,
        "product_review_form": product_review_form,
        "avg_rating_data": avg_rating_data,
        "rating_width": rating_width,
        "progres_data": progres_data,
    }

    return render(request, "core/product-detail.html", context)


# Category Views
def category_list_view(request):
    # categories = Category.objects.all()
    categories = Category.objects.all().annotate(product_count=Count("products"))

    context = {
        "categories": categories,
    }

    return render(request, "core/category-list.html", context)


def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(
        product_status="published", category=category
    ).order_by("-date")

    context = {
        "products": products,
        "category": category,
    }

    return render(request, "core/category-product-list.html", context)


# Vendor Views
def vendor_list_view(request):
    vendors = Vendor.objects.all()

    context = {
        "vendors": vendors,
    }

    return render(request, "core/vendor-list.html", context)


def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    # vendor = get_object_or_404(Vendor, vid=vid)
    products = Product.objects.filter(
        vendor=vendor, product_status="published"
    ).order_by("-date")

    context = {
        "vendor": vendor,
        "products": products,
    }

    return render(request, "core/vendor-detail.html", context)


# Other Views
def tag_list_view(request, tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-date")

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        "products": products,
        "tag": tag,
    }

    return render(request, "core/tag.html", context)


def ajax_add_review(request, pid):
    if not request.user.is_authenticated:
        return JsonResponse(
            {"bool": False, "error": "Anda harus login untuk memberi review."}
        )

    product = Product.objects.get(pk=pid)
    user = request.user

    review = ProductReview.objects.create(
        user=user,
        product=product,
        review=request.POST["review"],
        rating=request.POST["rating"],
    )

    average_reviews = ProductReview.objects.filter(product=product).aggregate(
        rating=Avg("rating")
    )

    context = {
        "user": user.username,
        "review": request.POST["review"],
        "rating": request.POST["rating"],
    }

    return JsonResponse(
        {
            "bool": True,
            "context": context,
            "average_reviews": average_reviews,
        }
    )


def search_view(request):
    query = request.GET.get("q")
    cat_cid = request.GET.get("category")
    products = Product.objects.filter(
        Q(title__icontains=query) | Q(description__icontains=query)
    ).order_by("-date")

    if cat_cid:
        products = products.filter(category__cid=cat_cid)

    context = {"products": products, "query": query}

    return render(request, "core/search.html", context)


def filter_product(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")
    min_price = request.GET.get("min_price")
    max_price = request.GET.get("max_price")

    products = (
        Product.objects.filter(product_status="published").order_by("-id").distinct()
    )

    if min_price and max_price:
        products = products.filter(price__gte=min_price, price__lte=max_price)

    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()

    data = render_to_string("core/async/product-list.html", {"products": products})
    count = products.count()

    return JsonResponse({"data": data, "count": count})


def add_to_cart(request):
    cart_product = {}

    product_id = str(request.GET["id"])

    try:
        new_qty = int(request.GET["qty"])
        if new_qty < 1:
            new_qty = 1
    except (ValueError, TypeError):
        new_qty = 1

    cart_product[str(request.GET["id"])] = {
        "title": request.GET["title"],
        "qty": new_qty,
        "price": request.GET["price"],
        "pid": request.GET["pid"],
        "image": request.GET["image"],
    }

    if "cart_data_obj" in request.session:
        if product_id in request.session["cart_data_obj"]:
            cart_data = request.session["cart_data_obj"]

            current_qty = int(cart_data[product_id]["qty"])
            cart_data[product_id]["qty"] = current_qty + new_qty

            # cart_data[str(request.GET["id"])]["qty"] = int(
            #     cart_product[str(request.GET["id"])]["qty"]
            # )
            # cart_data.update(cart_data)
            request.session["cart_data_obj"] = cart_data
        else:
            cart_data = request.session["cart_data_obj"]
            cart_data.update(cart_product)
            request.session["cart_data_obj"] = cart_data
    else:
        request.session["cart_data_obj"] = cart_product

    return JsonResponse(
        {
            "data": request.session["cart_data_obj"],
            "totalcartitems": len(request.session["cart_data_obj"]),
        }
    )


def cart_view(request):
    cart_total_amount = 0

    if "cart_data_obj" in request.session:
        for product_id, item in request.session["cart_data_obj"].items():
            price_rep = item["price"].strip().replace(",", "")
            subtotal = int(price_rep) * int(item["qty"])
            item["price"] = price_rep
            item["subtotal"] = subtotal
            cart_total_amount += subtotal
        return render(
            request,
            "core/cart.html",
            {
                "cart_data": request.session["cart_data_obj"],
                "totalcartitems": len(request.session["cart_data_obj"]),
                "cart_total_amount": cart_total_amount,
            },
        )
    else:
        return render(
            request,
            "core/cart.html",
            {
                "cart_data": {},
                "totalcartitems": 0,
                "cart_total_amount": cart_total_amount,
            },
        )


def delete_item_from_cart(request):
    product_id = str(request.GET["id"])

    if "cart_data_obj" in request.session:
        if product_id in request.session["cart_data_obj"]:
            cart_data = request.session["cart_data_obj"]
            del request.session["cart_data_obj"][product_id]
            request.session["cart_data_obj"] = cart_data

    cart_total_amount = 0
    if "cart_data_obj" in request.session:
        for product_id, item in request.session["cart_data_obj"].items():
            price_rep = item["price"].strip().replace(",", "")
            subtotal = int(price_rep) * int(item["qty"])
            item["price"] = price_rep
            item["subtotal"] = subtotal
            cart_total_amount += subtotal

    context = render_to_string(
        "core/async/cart-list.html",
        {
            "cart_data": request.session["cart_data_obj"],
            "totalcartitems": len(request.session["cart_data_obj"]),

ecommerce/templates/core/async/product-list.html
{% for product in products %}
<div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
  <div class="product-cart-wrap mb-30">
    <div class="product-img-action-wrap">
      <div class="product-img product-img-zoom">
        <a href="{% url 'core:product-detail' product.pid %}">
          <img
            class="default-img"
            src="{{ product.image.url }}"
            alt="{{ product.title }}"
          />
          <img
            class="hover-img"
            src="{{ product.image.url }}"
            alt="{{ product.title }}"
          />
        </a>
      </div>
      <div class="product-action-1">
        <a
          aria-label="Add To Wishlist"
          class="action-btn"
          href="shop-wishlist.html"
          ><i class="fi-rs-heart"></i
        ></a>
        <a aria-label="Compare" class="action-btn" href="shop-compare.html"
          ><i class="fi-rs-shuffle"></i
        ></a>
        <a
          aria-label="Quick view"
          class="action-btn"
          data-bs-toggle="modal"
          data-bs-target="#quickViewModal"
          ><i class="fi-rs-eye"></i
        ></a>
      </div>
      <!-- prettier-ignore -->
      {% with percentage=product.get_percentage %}
                {% if percentage != 0 %}
      <div class="product-badges product-badges-position product-badges-mrg">
        <span class="hot"> -{{ percentage|floatformat:0 }}% </span>
      </div>
      {% endif %}
      <!-- prettier-ignore -->
      {% endwith %}
    </div>
    <div class="product-content-wrap">
      <div class="product-category">
        <a href="{% url 'core:category-product-list' product.category.cid %}"
          >{{ product.category.title }}</a
        >
      </div>
      <h2>
        <a href="{% url 'core:product-detail' product.pid %}"
          >{{ product.title|truncatechars:50 }}
        </a>
      </h2>
      <div class="product-rate-cover">
        <div class="product-rate d-inline-block">
          <div
            class="product-rating"
            style="width: {{ product.rating_star }}%"
          ></div>
        </div>
        <span class="font-small ml-5 text-muted">
          <!-- prettier-ignore -->
          {% if product.avg_rating %}
                    ({{ product.avg_rating|floatformat:1 }})
                    {% else %}
                    (0)
                    {% endif %}
        </span>
      </div>
      <div>
        <span class="font-small text-muted"
          >By
          <a href="{% url 'core:vendor-detail' product.vendor.vid %}"
            >{{ product.vendor.title }}</a
          ></span
        >
      </div>
      <div class="product-card-bottom">
        {% load humanize %}
        <div class="product-price">
          <span>Rp</span>
          <span class="current-product-price-{{ product.id }}">
            {{ product.price|floatformat:0|intcomma }}
          </span>
          {% with old_price=product.old_price %}
          <!-- prettier-ignore -->
          {% if old_price != 0 %}
          <span class="old-price">
            Rp{{ old_price|floatformat:0|intcomma }}
          </span>
          {% endif %}
          <!-- prettier-ignore -->
          {% endwith %}
        </div>
        <div class="add-cart">
          <input
            type="hidden"
            value="1"
            name=""
            id="product-quantity"
            class="product-quantity-{{ product.id }}"
          />
          <input
            type="hidden"
            value="{{ product.pid }}"
            name=""
            id=""
            class="product-pid-{{ product.id }}"
          />
          <input
            type="hidden"
            value="{{ product.image.url }}"
            name=""
            id=""
            class="product-image-{{ product.id }}"
          />
          <input
            type="hidden"
            value="{{ product.id }}"
            name=""
            id=""
            class="product-id-{{ product.id }}"
          />
          <input
            type="hidden"
            value="{{ product.title }}"
            name=""
            id=""
            class="product-title-{{ product.id }}"
          />
          <button
            class="add add-to-cart-btn"
            id="add-to-cart-btn"
            data-index="{{ product.id }}"
          >
            <i class="fi-rs-shopping-cart mr-5"></i>
            Add
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
<!--end product card-->
{% endfor %}